table DimCustomer

	column CustomerID
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerID

	column State
		dataType: string
		sourceColumn: State

	column OrderN
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: OrderN


	partition DimCustomer = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/DimCustomer.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"CustomerID", type text}, {"State", type text}, {"OrderN", Int64.Type}})
			in
				#"Changed Type"
