table DimProduct

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category

	column OrderN
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: OrderN

	column LateRate
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: LateRate

	column AvgLeadTime
		dataType: double
		formatString: #,0.0
		summarizeBy: none
		sourceColumn: AvgLeadTime


	partition DimProduct = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/DimProduct.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Category", type text}, {"OrderN", Int64.Type}, {"LateRate", type number}, {"AvgLeadTime", type number}})
			in
				#"Changed Type"
