table DimSeller

	measure Sellers = COUNTROWS(DimSeller)
		formatString: #,0

	measure 'High Risk Sellers' = CALCULATE([Sellers], DimSeller[RiskBand] = "High")
		formatString: #,0

	measure 'Seller Order N' = SUM(DimSeller[OrderN])
		formatString: #,0

	measure 'Seller Late Rate' = AVERAGE(DimSeller[LateRate])
		formatString: 0.0%

	measure 'Seller Avg Freight' = AVERAGE(DimSeller[AvgFreight])
		formatString: #,0.00

	column SellerID
		dataType: string
		summarizeBy: none
		sourceColumn: SellerID

	column OrderN
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: OrderN

	column LateRate
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: LateRate

	column AvgFreight
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: AvgFreight

	column AvgLeadTime
		dataType: double
		formatString: #,0.0
		summarizeBy: none
		sourceColumn: AvgLeadTime

	column CustomerStateN
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: CustomerStateN

	column City
		dataType: string
		sourceColumn: City

	column State
		dataType: string
		sourceColumn: State

	column RiskBand
		dataType: string
		sourceColumn: RiskBand

	column RecommendedAction
		dataType: string
		sourceColumn: RecommendedAction

	column RiskRank
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: RiskRank


	partition DimSeller = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/DimSeller.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"SellerID", type text}, {"OrderN", Int64.Type}, {"LateRate", type number}, {"AvgFreight", type number}, {"AvgLeadTime", type number}, {"CustomerStateN", Int64.Type}, {"City", type text}, {"State", type text}, {"RiskBand", type text}, {"RecommendedAction", type text}, {"RiskRank", Int64.Type}})
			in
				#"Changed Type"
