table FactDemandWeekly

	measure 'Weekly Orders' = SUM(FactDemandWeekly[Orders])
		formatString: #,0

	column WeekStart
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: WeekStart

	column Orders
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: Orders


	partition FactDemandWeekly = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/FactDemandWeekly.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"WeekStart", type date}, {"Orders", Int64.Type}})
			in
				#"Changed Type"
