table FactOrders

	measure Orders = COUNTROWS(FactOrders)
		formatString: #,0

	measure 'OnTime Orders' = CALCULATE([Orders], FactOrders[OnTime] = 1)
		formatString: #,0

	measure 'On-time %' = DIVIDE([OnTime Orders], [Orders])
		formatString: 0.0%

	measure 'Late Orders' = CALCULATE([Orders], FactOrders[LateFlag] = 1)
		formatString: #,0

	measure 'Avg Lead Time' = AVERAGE(FactOrders[LeadTimeDays])
		formatString: #,0.0

	measure 'Avg Freight' = AVERAGE(FactOrders[Freight])
		formatString: #,0.00

	column OrderID
		dataType: string
		summarizeBy: none
		sourceColumn: OrderID

	column CustomerID
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerID

	column OrderDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: OrderDate

	column SellerID
		dataType: string
		summarizeBy: none
		sourceColumn: SellerID

	column CustomerState
		dataType: string
		sourceColumn: CustomerState

	column SellerState
		dataType: string
		sourceColumn: SellerState

	column Category
		dataType: string
		sourceColumn: Category

	column OnTime
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: OnTime

	column LateFlag
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: LateFlag

	column LeadTimeDays
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: LeadTimeDays

	column Freight
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Freight

	column ItemCount
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ItemCount

	column SellerCount
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SellerCount


	partition FactOrders = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/FactOrders.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"OrderID", type text}, {"CustomerID", type text}, {"OrderDate", type date}, {"SellerID", type text}, {"CustomerState", type text}, {"SellerState", type text}, {"Category", type text}, {"OnTime", Int64.Type}, {"LateFlag", Int64.Type}, {"LeadTimeDays", Int64.Type}, {"Freight", type number}, {"ItemCount", Int64.Type}, {"SellerCount", Int64.Type}})
			in
				#"Changed Type"
