table FactCorridor

	column SellerState
		dataType: string
		summarizeBy: none
		sourceColumn: SellerState

	column CustomerState
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerState

	column Orders
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: Orders

	column LateRate
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: LateRate

	column AvgLeadTime
		dataType: double
		formatString: #,0.0
		summarizeBy: none
		sourceColumn: AvgLeadTime

	column AvgFreight
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: AvgFreight


	partition FactCorridor = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/FactCorridor.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"SellerState", type text}, {"CustomerState", type text}, {"Orders", Int64.Type}, {"LateRate", type number}, {"AvgLeadTime", type number}, {"AvgFreight", type number}})
			in
				#"Changed Type"
