table ModelMetrics

	measure 'Holdout MAPE' = MAX(ModelMetrics[HoldoutMAPE])
		formatString: 0.0%

	measure 'Coverage 80' = MAX(ModelMetrics[Coverage80])
		formatString: 0.0%

	measure 'Coverage 95' = MAX(ModelMetrics[Coverage95])
		formatString: 0.0%

	column HoldoutMAPE
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: HoldoutMAPE

	column Coverage80
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: Coverage80

	column Coverage95
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: Coverage95

	column Method
		dataType: string
		sourceColumn: Method

	column HorizonWeeks
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: HorizonWeeks

	column HoldoutWeeks
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: HoldoutWeeks

	column SampleN
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: SampleN

	column WeekCount
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: WeekCount


	partition ModelMetrics = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/ModelMetrics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"HoldoutMAPE", type number}, {"Coverage80", type number}, {"Coverage95", type number}, {"Method", type text}, {"HorizonWeeks", Int64.Type}, {"HoldoutWeeks", Int64.Type}, {"SampleN", Int64.Type}, {"WeekCount", Int64.Type}})
			in
				#"Changed Type"
