table DimCompany

	column Ticker
		dataType: string
		sourceColumn: Ticker

	column YahooSymbol
		dataType: string
		sourceColumn: YahooSymbol

	column CompanyName
		dataType: string
		sourceColumn: CompanyName

	column Country
		dataType: string
		sourceColumn: Country

	column Sector
		dataType: string
		sourceColumn: Sector

	column Industry
		dataType: string
		sourceColumn: Industry

	column MarketCapEURm
		dataType: double
		formatString: #,0
		summarizeBy: sum
		sourceColumn: MarketCapEURm


	partition DimCompany = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/DimCompany.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Ticker", type text}, {"YahooSymbol", type text}, {"CompanyName", type text}, {"Country", type text}, {"Sector", type text}, {"Industry", type text}, {"MarketCapEURm", type number}})
			in
				#"Changed Type"
