table FactPrices

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		dataCategory: Time
		sourceColumn: Date
	column Ticker
		dataType: string
		sourceColumn: Ticker
	column Open
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Open
	column High
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: High
	column Low
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Low
	column Close
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Close
	column Volume
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: Volume
	column PrevClose
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: PrevClose
	column Change
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Change
	column ChangePct
		dataType: double
		formatString: 0.00
		summarizeBy: none
		sourceColumn: ChangePct
	column MarketCapEURm
		dataType: double
		formatString: #,0
		summarizeBy: sum
		sourceColumn: MarketCapEURm
	column SMA20
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: SMA20
	column SMA50
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: SMA50
	column EMA12
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: EMA12
	column EMA26
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: EMA26
	column MACD
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: MACD
	column MACDSignal
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: MACDSignal
	column MACDHist
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: MACDHist
	column RSI14
		dataType: double
		formatString: 0.0
		summarizeBy: none
		sourceColumn: RSI14
	column BBMid
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: BBMid
	column BBUpper
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: BBUpper
	column BBLower
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: BBLower
	column IsLatest
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: IsLatest

	measure Advancers = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1, FactPrices[ChangePct] > 0 )
		formatString: "#,0"

	measure Decliners = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1, FactPrices[ChangePct] < 0 )
		formatString: "#,0"

	measure Universe Count = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1 )
		formatString: "#,0"

	measure Avg Day Change % = CALCULATE( AVERAGE( FactPrices[ChangePct] ), FactPrices[IsLatest] = 1 )
		formatString: "0.00"

	measure Market Cap Latest EURm = CALCULATE( SUM( FactPrices[MarketCapEURm] ), FactPrices[IsLatest] = 1 )
		formatString: "#,0"

	measure Last Close = CALCULATE( AVERAGE( FactPrices[Close] ), FactPrices[IsLatest] = 1 )
		formatString: "#,0.00"

	measure Last Change % = CALCULATE( AVERAGE( FactPrices[ChangePct] ), FactPrices[IsLatest] = 1 )
		formatString: "0.00"

	measure Last RSI = CALCULATE( AVERAGE( FactPrices[RSI14] ), FactPrices[IsLatest] = 1 )
		formatString: "0.0"

	measure Last Volume = CALCULATE( SUM( FactPrices[Volume] ), FactPrices[IsLatest] = 1 )
		formatString: "#,0"

	measure Close = AVERAGE( FactPrices[Close] )
		formatString: "#,0.00"

	measure SMA 20 = AVERAGE( FactPrices[SMA20] )
		formatString: "#,0.00"

	measure SMA 50 = AVERAGE( FactPrices[SMA50] )
		formatString: "#,0.00"

	measure BB Upper = AVERAGE( FactPrices[BBUpper] )
		formatString: "#,0.00"

	measure BB Lower = AVERAGE( FactPrices[BBLower] )
		formatString: "#,0.00"

	measure MACD Line = AVERAGE( FactPrices[MACD] )
		formatString: "0.0000"

	measure MACD Signal = AVERAGE( FactPrices[MACDSignal] )
		formatString: "0.0000"

	measure MACD Hist = AVERAGE( FactPrices[MACDHist] )
		formatString: "0.0000"

	measure RSI 14 = AVERAGE( FactPrices[RSI14] )
		formatString: "0.0"

	measure Volume = SUM( FactPrices[Volume] )
		formatString: "#,0"

	measure Day Change % Latest = CALCULATE( AVERAGE( FactPrices[ChangePct] ), FactPrices[IsLatest] = 1 )
		formatString: "0.00"


	partition FactPrices = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/FactPrices.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Ticker", type text}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Volume", Int64.Type}, {"PrevClose", type number}, {"Change", type number}, {"ChangePct", type number}, {"MarketCapEURm", type number}, {"SMA20", type number}, {"SMA50", type number}, {"EMA12", type number}, {"EMA26", type number}, {"MACD", type number}, {"MACDSignal", type number}, {"MACDHist", type number}, {"RSI14", type number}, {"BBMid", type number}, {"BBUpper", type number}, {"BBLower", type number}, {"IsLatest", Int64.Type}})
			in
				#"Changed Type"
