table FactPrices

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		dataCategory: Time
		sourceColumn: Date
	column Ticker
		dataType: string
		sourceColumn: Ticker
	column Open
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Open
	column High
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: High
	column Low
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Low
	column Close
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Close
	column Volume
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: Volume
	column PrevClose
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: PrevClose
	column Change
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: Change
	column ChangePct
		dataType: double
		formatString: 0.00
		summarizeBy: none
		sourceColumn: ChangePct
	column MarketCapEURm
		dataType: double
		formatString: #,0
		summarizeBy: sum
		sourceColumn: MarketCapEURm
	column SMA20
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: SMA20
	column SMA50
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: SMA50
	column EMA12
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: EMA12
	column EMA26
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: EMA26
	column MACD
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: MACD
	column MACDSignal
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: MACDSignal
	column MACDHist
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: MACDHist
	column RSI14
		dataType: double
		formatString: 0.0
		summarizeBy: none
		sourceColumn: RSI14
	column BBMid
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: BBMid
	column BBUpper
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: BBUpper
	column BBLower
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: BBLower
	column IsLatest
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: IsLatest

	column StrategySide
		dataType: string
		sourceColumn: StrategySide

	column IsSignal
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: IsSignal

	column NextDayReturnPct
		dataType: double
		formatString: 0.00
		summarizeBy: none
		sourceColumn: NextDayReturnPct

	column SignalHit
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SignalHit

	measure Advancers = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1, FactPrices[ChangePct] > 0 )
		formatString: #,0

	measure Decliners = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1, FactPrices[ChangePct] < 0 )
		formatString: #,0

	measure 'Universe Count' = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1 )
		formatString: #,0

	measure 'Avg Day Change %' = CALCULATE( AVERAGE( FactPrices[ChangePct] ), FactPrices[IsLatest] = 1 )
		formatString: 0.00

	measure 'Market Cap Latest EURm' = CALCULATE( SUM( FactPrices[MarketCapEURm] ), FactPrices[IsLatest] = 1 )
		formatString: #,0

	measure 'Last Close' = CALCULATE( AVERAGE( FactPrices[Close] ), FactPrices[IsLatest] = 1 )
		formatString: #,0.00

	measure 'Last Change %' = CALCULATE( AVERAGE( FactPrices[ChangePct] ), FactPrices[IsLatest] = 1 )
		formatString: 0.00

	measure 'Last RSI' = CALCULATE( AVERAGE( FactPrices[RSI14] ), FactPrices[IsLatest] = 1 )
		formatString: 0.0

	measure 'Last Volume' = CALCULATE( SUM( FactPrices[Volume] ), FactPrices[IsLatest] = 1 )
		formatString: #,0

	measure 'Close Price' = AVERAGE( FactPrices[Close] )
		formatString: #,0.00

	measure 'SMA 20' = AVERAGE( FactPrices[SMA20] )
		formatString: #,0.00

	measure 'SMA 50' = AVERAGE( FactPrices[SMA50] )
		formatString: #,0.00

	measure 'BB Upper' = AVERAGE( FactPrices[BBUpper] )
		formatString: #,0.00

	measure 'BB Lower' = AVERAGE( FactPrices[BBLower] )
		formatString: #,0.00

	measure 'MACD Line' = AVERAGE( FactPrices[MACD] )
		formatString: 0.0000

	measure 'MACD Signal' = AVERAGE( FactPrices[MACDSignal] )
		formatString: 0.0000

	measure 'MACD Hist' = AVERAGE( FactPrices[MACDHist] )
		formatString: 0.0000

	measure 'RSI 14' = AVERAGE( FactPrices[RSI14] )
		formatString: 0.0

	measure 'Volume Sum' = SUM( FactPrices[Volume] )
		formatString: #,0

	measure 'Day Change % Latest' = CALCULATE( AVERAGE( FactPrices[ChangePct] ), FactPrices[IsLatest] = 1 )
		formatString: 0.00

	/// RSI mean-reversion desk — Long when RSI≤30, Short when RSI≥70; hit vs next-day return.
	measure 'Long Signals Today' = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1, FactPrices[StrategySide] = "Long" )
		formatString: #,0

	measure 'Short Signals Today' = CALCULATE( DISTINCTCOUNT( FactPrices[Ticker] ), FactPrices[IsLatest] = 1, FactPrices[StrategySide] = "Short" )
		formatString: #,0

	measure 'Long Hit Rate %' = DIVIDE( CALCULATE( SUM( FactPrices[SignalHit] ), FactPrices[StrategySide] = "Long", NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) ), CALCULATE( COUNTROWS( FactPrices ), FactPrices[StrategySide] = "Long", NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) ) ) * 100
		formatString: 0.0

	measure 'Short Hit Rate %' = DIVIDE( CALCULATE( SUM( FactPrices[SignalHit] ), FactPrices[StrategySide] = "Short", NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) ), CALCULATE( COUNTROWS( FactPrices ), FactPrices[StrategySide] = "Short", NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) ) ) * 100
		formatString: 0.0

	measure 'Avg Next-Day % Long' = CALCULATE( AVERAGE( FactPrices[NextDayReturnPct] ), FactPrices[StrategySide] = "Long" )
		formatString: 0.00

	measure 'Avg Next-Day % Short' = CALCULATE( AVERAGE( FactPrices[NextDayReturnPct] ), FactPrices[StrategySide] = "Short" )
		formatString: 0.00

	measure 'Signal Count' = CALCULATE( COUNTROWS( FactPrices ), FactPrices[IsSignal] = 1, NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) )
		formatString: #,0

	measure 'Next-Day Return %' = AVERAGE( FactPrices[NextDayReturnPct] )
		formatString: 0.00

	/// Equal-weight desk P&L: Long = +next-day %, Short = −next-day % (same unit bet per suggestion).
	measure 'Strategy Day Return %' = AVERAGEX( FILTER( FactPrices, FactPrices[IsSignal] = 1 && NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) ), IF( FactPrices[StrategySide] = "Long", FactPrices[NextDayReturnPct], IF( FactPrices[StrategySide] = "Short", -FactPrices[NextDayReturnPct], BLANK() ) ) )
		formatString: 0.00

	measure 'Strategy EW Avg Return %' = [Strategy Day Return %]
		formatString: 0.00

	measure 'Strategy Cumulative Return %' = VAR _d = MAX( DimDate[Date] ) VAR _hist = FILTER( ALLSELECTED( DimDate[Date] ), DimDate[Date] <= _d ) VAR _prod = PRODUCTX( _hist, VAR _r = CALCULATE( [Strategy Day Return %] ) RETURN IF( ISBLANK( _r ), 1, 1 + _r / 100 ) ) RETURN ( _prod - 1 ) * 100
		formatString: 0.00

	measure 'Strategy Hit Rate %' = DIVIDE( CALCULATE( SUM( FactPrices[SignalHit] ), FactPrices[IsSignal] = 1, NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) ), [Signal Count] ) * 100
		formatString: 0.0

	/// First / last signal day with a known next-day outcome (equal-weight backtest window).
	measure 'Strategy First Signal Date' = CALCULATE( MIN( FactPrices[Date] ), FactPrices[IsSignal] = 1, NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) )
		formatString: YYYY-MM-DD

	measure 'Strategy Last Signal Date' = CALCULATE( MAX( FactPrices[Date] ), FactPrices[IsSignal] = 1, NOT( ISBLANK( FactPrices[NextDayReturnPct] ) ) )
		formatString: YYYY-MM-DD

	measure 'Strategy Backtest Days' = VAR _d0 = [Strategy First Signal Date] VAR _d1 = [Strategy Last Signal Date] RETURN IF( ISBLANK( _d0 ) || ISBLANK( _d1 ), BLANK(), DATEDIFF( _d0, _d1, DAY ) )
		formatString: #,0

	measure 'Strategy Backtest Period' = VAR _days = [Strategy Backtest Days] RETURN IF( ISBLANK( _days ), BLANK(), FORMAT( _days, "#,0" ) & " days" )

	measure 'Strategy Cumulative Card' = VAR _pct = [Strategy Cumulative Return %] VAR _period = [Strategy Backtest Period] RETURN IF( ISBLANK( _pct ), BLANK(), FORMAT( _pct, "0.00" ) & "%" & UNICHAR( 10 ) & _period )

	/// Latest price session (IsLatest = 1) — used instead of “today” on Signal Desk.
	measure 'Latest Session Date' = CALCULATE( MAX( FactPrices[Date] ), FactPrices[IsLatest] = 1 )
		formatString: YYYY-MM-DD

	measure 'Long Signals Card' = [Long Signals Today]
		formatString: #,0

	measure 'Short Signals Card' = [Short Signals Today]
		formatString: #,0


	partition FactPrices = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/FactPrices.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Ticker", type text}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Volume", Int64.Type}, {"PrevClose", type number}, {"Change", type number}, {"ChangePct", type number}, {"MarketCapEURm", type number}, {"SMA20", type number}, {"SMA50", type number}, {"EMA12", type number}, {"EMA26", type number}, {"MACD", type number}, {"MACDSignal", type number}, {"MACDHist", type number}, {"RSI14", type number}, {"BBMid", type number}, {"BBUpper", type number}, {"BBLower", type number}, {"IsLatest", Int64.Type}, {"StrategySide", type text}, {"IsSignal", Int64.Type}, {"NextDayReturnPct", type number}, {"SignalHit", Int64.Type}})
			in
				#"Changed Type"
