table DimCity
	lineageTag: 9ccf261c-fecc-4ddd-a701-8ef62b123982

	column City
		dataType: string
		lineageTag: d078b375-aa9c-419b-9b62-b403238eb63d
		sourceColumn: City

	column Latitude
		dataType: double
		lineageTag: 2a53a352-7b14-439a-b05c-42f4153b812e
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: Latitude

	column Longitude
		dataType: double
		lineageTag: ba41e504-f7a1-4f9c-92d4-fc96fa31709e
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: Longitude

	column Country
		dataType: string
		lineageTag: 0e195611-2bd3-4dd1-b092-983b9785ee06
		sourceColumn: Country

	partition DimCity = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(GoldDataFolder & "/DimCity.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"City", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Country", type text}})
				in
					#"Changed Type"

