table DimDate
	lineageTag: 4889cfbf-8e63-4709-816b-1ed5fdf2a0f2
	dataCategory: Time

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 9d6de4c4-3723-4a6e-87ed-d1c2182e5694
		dataCategory: Time
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 21743d48-b94b-43b1-9f74-ef6e8c8ee64b
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4a08cbdd-651e-43ae-a8ae-241c5f01d33c
		summarizeBy: none
		sourceColumn: Month

	column MonthName
		dataType: string
		lineageTag: 2c2a5fa9-1a70-40d0-968d-c2cf6d2a5f2d
		sourceColumn: MonthName
		sortByColumn: Month

	column YearMonth
		dataType: string
		lineageTag: aeeb8892-0a79-494c-924f-fd9b48164a77
		sourceColumn: YearMonth
		sortByColumn: MonthYearSort

	column Quarter
		dataType: string
		lineageTag: 527946a3-e546-4cb1-a34b-f40e85259826
		sourceColumn: Quarter

	column YearQuarter
		dataType: string
		lineageTag: ea512af8-0185-433b-a521-8ed448f9cffc
		sourceColumn: YearQuarter

	column Day
		dataType: int64
		formatString: 0
		lineageTag: eed8766a-9d4a-4951-9ec6-d496125d0419
		summarizeBy: none
		sourceColumn: Day

	column MonthYearSort
		dataType: int64
		isHidden
		lineageTag: 9cc87e50-faf6-4e0a-a285-f5fec119762e
		summarizeBy: none
		sourceColumn: MonthYearSort

	partition DimDate = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(GoldDataFolder & "/DimDate.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"YearMonth", type text}, {"Quarter", type text}, {"YearQuarter", type text}, {"Day", Int64.Type}, {"MonthYearSort", Int64.Type}})
				in
					#"Changed Type"

