table DimDate
	dataCategory: Time

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		dataCategory: Time
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: Month

	column MonthName
		dataType: string
		sortByColumn: Month
		sourceColumn: MonthName

	column YearMonth
		dataType: string
		sortByColumn: MonthYearSort
		sourceColumn: YearMonth

	column Quarter
		dataType: string
		sourceColumn: Quarter

	column YearQuarter
		dataType: string
		sourceColumn: YearQuarter

	column Day
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Day

	column MonthYearSort
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: MonthYearSort


	partition DimDate = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/DimDate.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"YearMonth", type text}, {"Quarter", type text}, {"YearQuarter", type text}, {"Day", Int64.Type}, {"MonthYearSort", Int64.Type}})
			in
				#"Changed Type"
