table DimPatient

	column patient_nbr
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: patient_nbr

	column Race
		dataType: string
		sourceColumn: Race

	column Gender
		dataType: string
		sourceColumn: Gender

	column AgeBand
		dataType: string
		sourceColumn: AgeBand

	column EncounterCount
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: EncounterCount


	partition DimPatient = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/DimPatient.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"patient_nbr", Int64.Type}, {"Race", type text}, {"Gender", type text}, {"AgeBand", type text}, {"EncounterCount", Int64.Type}})
			in
				#"Changed Type"
