table FactPathwayBridge

	measure 'Pathway Weight' = SUM(FactPathwayBridge[Weight])
		formatString: #,0

	column Source
		dataType: string
		sourceColumn: Source

	column Target
		dataType: string
		sourceColumn: Target

	column Weight
		dataType: int64
		formatString: 0
		sourceColumn: Weight

	column Hop
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Hop


	partition FactPathwayBridge = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/FactPathwayBridge.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Source", type text}, {"Target", type text}, {"Weight", Int64.Type}, {"Hop", Int64.Type}})
			in
				#"Changed Type"
