table FactHeatBridge

	measure 'Heat Encounters' = SUM(FactHeatBridge[Encounters])
		formatString: #,0

	measure 'Heat Readmit Rate' = DIVIDE(SUM(FactHeatBridge[Readmit30]), SUM(FactHeatBridge[Encounters]))
		formatString: 0.0%

	column AgeBand
		dataType: string
		sourceColumn: AgeBand

	column DiagGroup
		dataType: string
		sourceColumn: DiagGroup

	column Encounters
		dataType: int64
		formatString: 0
		sourceColumn: Encounters

	column Readmit30
		dataType: int64
		formatString: 0
		sourceColumn: Readmit30

	column ReadmitRate
		dataType: double
		formatString: 0.0%
		sourceColumn: ReadmitRate


	partition FactHeatBridge = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(GoldDataFolder & "/FactHeatBridge.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"AgeBand", type text}, {"DiagGroup", type text}, {"Encounters", Int64.Type}, {"Readmit30", Int64.Type}, {"ReadmitRate", type number}})
			in
				#"Changed Type"
