table FactGradeBridge

	measure 'Grade Default Rate' = AVERAGE(FactGradeBridge[DefaultRate])
		formatString: 0.0%

	measure 'Grade Avg PD' = AVERAGE(FactGradeBridge[AvgPD])
		formatString: 0.0%

	column Grade
		dataType: string
		sortByColumn: GradeSort
		sourceColumn: Grade

	column GradeSort
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: GradeSort

	column Applications
		dataType: int64
		formatString: #,0
		summarizeBy: none
		sourceColumn: Applications

	column DefaultRate
		dataType: double
		formatString: 0.0%
		sourceColumn: DefaultRate

	column AvgPD
		dataType: double
		formatString: 0.0%
		sourceColumn: AvgPD

	column Exposure
		dataType: double
		formatString: #,0
		sourceColumn: Exposure

	column EL
		dataType: double
		formatString: #,0
		sourceColumn: EL


	partition FactGradeBridge = m
		mode: import
		source =
			let
				FolderPath = GoldDataFolder,
				FilePath = FolderPath & "/FactGradeBridge.csv",
				RawCsv = Csv.Document(File.Contents(FilePath), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				WithHeaders = Table.PromoteHeaders(RawCsv, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(WithHeaders, {{"Grade", type text}, {"GradeSort", Int64.Type}, {"Applications", Int64.Type}, {"DefaultRate", type number}, {"AvgPD", type number}, {"Exposure", type number}, {"EL", type number}})
			in
				Typed
